import { Texts } from './types';

export const TEXTS: { [key: string]: Texts } = {
  en: {
    headerTitle: 'Ziek Melder',
    formTitle: 'Report Sick Leave',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'e.g. Alex Doe',
    employerLabel: 'Employer',
    employerPlaceholder: 'e.g. Acme B.V.',
    startDateLabel: 'First day of sickness',
    sickLeaveTypeLabel: 'Type of leave',
    typeSelfLabel: 'I am sick',
    typeChildLabel: 'My child is sick',
    reasonLabel: 'Reason for absence',
    reasonPlaceholder: 'e.g. flu, personal reasons, injury',
    privacyNote: 'Note: Do not share sensitive medical details or specific diagnoses.',
    submitButton: 'Send Notification',
    submittingButton: 'Sending...',
    confirmationTitle: 'Notification Sent!',
    confirmationMessage: 'Your employer has been notified. A confirmation has been sent to your registered contact details. Get well soon!',
    confirmationDetailsTitle: 'Submission Summary',
    confirmationProof: 'Proof of notification (timestamp):',
    reportAnotherButton: 'Report Another Absence',
    requiredField: 'This field is required',
    homeHeroTitle: 'Sick? Report it in seconds.',
    homeHeroSubtitle: 'A fast, simple, and secure way to notify your employer when you are unable to work.',
    homeEmployeeCTA: 'Report Sick Leave Now',
    homeForCompanies: 'For Companies',
    homeCompanyTitle: 'Automate & Simplify',
    homeCompanyDescription: 'Streamline sick leave notifications, ensure compliance, and reduce administrative overhead. Integrate with your HR system.',
    homeCompanyCTA: 'Partner with Us',
    loginEmployee: 'Employee Login',
    loginCompany: 'Company Login',
    demoLoginTitle: 'Quick Demo Access',
    slide1Title: 'Focus on Recovery',
    slide1Desc: 'Reporting your sickness should be the last thing on your mind. We make it instant.',
    slide2Title: 'Fully Compliant',
    slide2Desc: 'GDPR and Dutch labor law ready. No medical data is ever stored.',
    slide3Title: 'Direct Integration',
    slide3Desc: 'Notifications go straight to HR systems or supervisors via Email, WhatsApp, or API.',
    howItWorksTitle: 'How it Works',
    howItWorksStep1: 'Notify us in 30 seconds',
    howItWorksStep2: 'Platform automates routing',
    howItWorksStep3: 'Company stays informed',
    pauseSlider: 'Pause slider',
    playSlider: 'Play slider',
    goToSlide: 'Go to slide',
    heroSliderLabel: 'Promotional content carousel',
    adminDashboardTitle: 'Admin Dashboard',
    totalCompanies: 'Total Companies',
    totalEmployees: 'Total Employees',
    activeSickReports: 'Active Sick Reports',
    registeredCompanies: 'Registered Companies',
    companyName: 'Company Name',
    contactPerson: 'Contact Person',
    employeeCount: 'Employees',
    companyDashboardTitle: 'Company Dashboard',
    welcomeMessage: 'Welcome',
    yourEmployees: 'Your Employees',
    sickReportsFor: 'Sick Leave Reports for',
    employeeName: 'Employee Name',
    leaveType: 'Leave Type',
    status: 'Status',
    viewDetails: 'Details',
    manageEmployees: 'Manage Employees',
    settings: 'Settings',
  },
  nl: {
    headerTitle: 'Ziek Melder',
    formTitle: 'Meld je ziek',
    fullNameLabel: 'Volledige Naam',
    fullNamePlaceholder: 'bijv. Alex de Wit',
    employerLabel: 'Werkgever',
    employerPlaceholder: 'bijv. Acme B.V.',
    startDateLabel: 'Eerste ziektedag',
    sickLeaveTypeLabel: 'Type verlof',
    typeSelfLabel: 'Ik ben ziek',
    typeChildLabel: 'Mijn kind is ziek',
    reasonLabel: 'Reden van afwezigheid',
    reasonPlaceholder: 'bijv. griep, persoonlijke redenen, blessure',
    privacyNote: 'Let op: Deel geen gevoelige medische details ou specifieke diagnoses.',
    submitButton: 'Verstuur Melding',
    submittingButton: 'Versturen...',
    confirmationTitle: 'Melding Verzonden!',
    confirmationMessage: 'Je werkgever is op de hoogte gesteld. Een bevestiging is verstuurd naar je geregistreerde contactgegevens. Beterschap!',
    confirmationDetailsTitle: 'Overzicht van melding',
    confirmationProof: 'Bewijs van melding (tijdstip):',
    reportAnotherButton: 'Nog een melding doen',
    requiredField: 'Dit veld is verplicht',
    homeHeroTitle: 'Ziek? Meld het in seconden.',
    homeHeroSubtitle: 'Een snelle, simpele en veilige manier om je werkgever te informeren als je niet kunt werken.',
    homeEmployeeCTA: 'Meld je nu ziek',
    homeForCompanies: 'Voor Bedrijven',
    homeCompanyTitle: 'Automatiseer & Vereenvoudig',
    homeCompanyDescription: 'Stroomlijn ziekmeldingen, waarborg compliance en verminder administratieve lasten. Integreer met uw HR-systeem.',
    homeCompanyCTA: 'Word Partner',
    loginEmployee: 'Login Werknemer',
    loginCompany: 'Login Bedrijf',
    demoLoginTitle: 'Snel Demo Toegang',
    slide1Title: 'Focus op Herstel',
    slide1Desc: 'Je ziekmelden moet het laatste zijn waar je aan denkt. Wij maken het direct geregeld.',
    slide2Title: 'Volledig Compliant',
    slide2Desc: 'Klaar voor de AVG en de Nederlandse arbeidswetgeving. Er worden geen medische gegevens opgeslagen.',
    slide3Title: 'Directe Koppeling',
    slide3Desc: 'Meldingen gaan direct naar HR-systemen of leidinggevenden via E-mail, WhatsApp of API.',
    howItWorksTitle: 'Hoe het Werkt',
    howItWorksStep1: 'Meld je in 30 seconden',
    howItWorksStep2: 'Platform automatiseert route',
    howItWorksStep3: 'Bedrijf is direct op de hoogte',
    pauseSlider: 'Pauzeer slider',
    playSlider: 'Speel slider af',
    goToSlide: 'Ga naar slide',
    heroSliderLabel: 'Promotionele inhoud carousel',
    adminDashboardTitle: 'Admin Dashboard',
    totalCompanies: 'Totaal Bedrijven',
    totalEmployees: 'Totaal Werknemers',
    activeSickReports: 'Actieve Ziekmeldingen',
    registeredCompanies: 'Geregistreerde Bedrijven',
    companyName: 'Bedrijfsnaam',
    contactPerson: 'Contactpersoon',
    employeeCount: 'Werknemers',
    companyDashboardTitle: 'Bedrijfsdashboard',
    welcomeMessage: 'Welkom',
    yourEmployees: 'Uw Werknemers',
    sickReportsFor: 'Ziekmeldingen voor',
    employeeName: 'Naam Werknemer',
    leaveType: 'Type Verlof',
    status: 'Status',
    viewDetails: 'Details',
    manageEmployees: 'Beheer Werknemers',
    settings: 'Instellingen',
  },
  pl: {
    headerTitle: 'Ziek Melder',
    formTitle: 'Zgłoś chorobę',
    fullNameLabel: 'Imię i nazwisko',
    fullNamePlaceholder: 'np. Jan Kowalski',
    employerLabel: 'Pracodawca',
    employerPlaceholder: 'np. Acme B.V.',
    startDateLabel: 'Pierwszy dzień choroby',
    sickLeaveTypeLabel: 'Rodzaj nieobecności',
    typeSelfLabel: 'Jestem chory',
    typeChildLabel: 'Moje dziecko jest chore',
    reasonLabel: 'Powód nieobecności',
    reasonPlaceholder: 'np. grypa, powody osobiste, kontuzja',
    privacyNote: 'Uwaga: Nie udostępniaj wrażliwych szczegółów medycznych ani konkretnych diagnoz.',
    submitButton: 'Wyślij powiadomienie',
    submittingButton: 'Wysyłanie...',
    confirmationTitle: 'Powiadomienie wysłane!',
    confirmationMessage: 'Twój pracodawca został powiadomiony. Potwierdzenie zostało wysłane na Twoje zarejestrowane dane kontaktowe. Szybkiego powrotu do zdrowia!',
    confirmationDetailsTitle: 'Podsumowanie zgłoszenia',
    confirmationProof: 'Dowód powiadomienia (znacznik czasu):',
    reportAnotherButton: 'Zgłoś kolejną nieobecność',
    requiredField: 'To pole jest wymagane',
    homeHeroTitle: 'Chory? Zgłoś to w kilka sekund.',
    homeHeroSubtitle: 'Szybki, prosty i bezpieczny sposób na powiadomienie pracodawcy o niezdolności do pracy.',
    homeEmployeeCTA: 'Zgłoś chorobę teraz',
    homeForCompanies: 'Dla firm',
    homeCompanyTitle: 'Automatyzacja i uproszczenie',
    homeCompanyDescription: 'Usprawnij powiadomienia o zwolnieniach lekarskich, zapewnij zgodność i zmniejsz obciążenie administracyjne. Zintegruj ze swoim systemem HR.',
    homeCompanyCTA: 'Współpracuj z nami',
    loginEmployee: 'Logowanie pracownika',
    loginCompany: 'Logowanie firmy',
    demoLoginTitle: 'Szybki dostęp demo',
    slide1Title: 'Skup się na powrocie do zdrowia',
    slide1Desc: 'Zgłoszenie choroby powinno być ostatnią rzeczą, o której myślisz. My robimy to natychmiast.',
    slide2Title: 'W pełnej zgodności',
    slide2Desc: 'Gotowy na RODO i holenderskie prawo pracy. Żadne dane medyczne nie są przechowywane.',
    slide3Title: 'Bezpośrednia integracja',
    slide3Desc: 'Powiadomienia trafiają prosto do systemów HR lub przełożonych przez e-mail, WhatsApp lub API.',
    howItWorksTitle: 'Jak to działa',
    howItWorksStep1: 'Powiadom nas w 30 sekund',
    howItWorksStep2: 'Platforma automatyzuje trasowanie',
    howItWorksStep3: 'Firma pozostaje poinformowana',
    pauseSlider: 'Wstrzymaj suwak',
    playSlider: 'Odtwórz suwak',
    goToSlide: 'Idź do slajdu',
    heroSliderLabel: 'Karuzela treści promocyjnych',
    adminDashboardTitle: 'Panel administratora',
    totalCompanies: 'Wszystkie firmy',
    totalEmployees: 'Wszyscy pracownicy',
    activeSickReports: 'Aktywne raporty chorobowe',
    registeredCompanies: 'Zarejestrowane firmy',
    companyName: 'Nazwa firmy',
    contactPerson: 'Osoba kontaktowa',
    employeeCount: 'Pracownicy',
    companyDashboardTitle: 'Panel firmy',
    welcomeMessage: 'Witaj',
    yourEmployees: 'Twoi pracownicy',
    sickReportsFor: 'Raporty chorobowe dla',
    employeeName: 'Nazwisko pracownika',
    leaveType: 'Rodzaj zwolnienia',
    status: 'Status',
    viewDetails: 'Szczegóły',
    manageEmployees: 'Zarządzaj pracownikami',
    settings: 'Ustawienia',
  },
  uk: {
    headerTitle: 'Ziek Melder',
    formTitle: 'Повідомити про хворобу',
    fullNameLabel: 'Повне ім\'я',
    fullNamePlaceholder: 'напр. Олександр Коваленко',
    employerLabel: 'Роботодавець',
    employerPlaceholder: 'напр. Acme B.V.',
    startDateLabel: 'Перший день хвороби',
    sickLeaveTypeLabel: 'Тип відпустки',
    typeSelfLabel: 'Я захворів(ла)',
    typeChildLabel: 'Моя дитина захворіла',
    reasonLabel: 'Причина відсутності',
    reasonPlaceholder: 'напр. грип, особисті причини, травма',
    privacyNote: 'Примітка: Не повідомляйте конфіденційні медичні подробиці або конкретні діагнози.',
    submitButton: 'Надіслати сповіщення',
    submittingButton: 'Надсилання...',
    confirmationTitle: 'Сповіщення надіслано!',
    confirmationMessage: 'Вашого роботодавця повідомлено. Підтвердження надіслано на ваші зареєстровані контактні дані. Одужуйте швидше!',
    confirmationDetailsTitle: 'Підсумок подання',
    confirmationProof: 'Підтвердження повідомлення (час):',
    reportAnotherButton: 'Повідомити про іншу відсутність',
    requiredField: 'Це поле є обов\'язковим',
    homeHeroTitle: 'Захворіли? Повідомте про це за секунди.',
    homeHeroSubtitle: 'Швидкий, простий і безпечний спосіб повідомити роботодавця про неможливість працювати.',
    homeEmployeeCTA: 'Повідомити про хворобу зараз',
    homeForCompanies: 'Для компаній',
    homeCompanyTitle: 'Автоматизуйте та спрощуйте',
    homeCompanyDescription: 'Оптимізуйте сповіщення про лікарняні, забезпечте відповідність вимогам і зменште адміністративні витрати. Інтегруйте зі своєю HR-системою.',
    homeCompanyCTA: 'Партнерство з нами',
    loginEmployee: 'Вхід для працівників',
    loginCompany: 'Вхід для компаній',
    demoLoginTitle: 'Швидкий доступ до демо',
    slide1Title: 'Зосередьтеся на одужанні',
    slide1Desc: 'Повідомлення про хворобу має бути останньою річчю, про яку ви думаєте. Ми робимо це миттєво.',
    slide2Title: 'Повна відповідність',
    slide2Desc: 'Готовність до GDPR та голландського трудового законодавства. Жодні медичні дані не зберігаються.',
    slide3Title: 'Пряма інтеграція',
    slide3Desc: 'Сповіщення надходять безпосередньо в HR-системи або керівникам через Email, WhatsApp або API.',
    howItWorksTitle: 'Як це працює',
    howItWorksStep1: 'Повідомте нас за 30 секунд',
    howItWorksStep2: 'Платформа автоматизує маршрутизацію',
    howItWorksStep3: 'Компанія залишається поінформованою',
    pauseSlider: 'Призупинити слайдер',
    playSlider: 'Відтворити слайдер',
    goToSlide: 'Перейти до слайда',
    heroSliderLabel: 'Карусель рекламного контенту',
    adminDashboardTitle: 'Панель адміністратора',
    totalCompanies: 'Всього компаній',
    totalEmployees: 'Всього працівників',
    activeSickReports: 'Активні звіти про хворобу',
    registeredCompanies: 'Зареєстровані компанії',
    companyName: 'Назва компанії',
    contactPerson: 'Контактна особа',
    employeeCount: 'Працівники',
    companyDashboardTitle: 'Панель компанії',
    welcomeMessage: 'Ласкаво просимо',
    yourEmployees: 'Ваші працівники',
    sickReportsFor: 'Звіти про хворобу для',
    employeeName: 'Ім\'я працівника',
    leaveType: 'Тип лікарняного',
    status: 'Status',
    viewDetails: 'Деталі',
    manageEmployees: 'Керування працівниками',
    settings: 'Налаштування',
  }
};